name: Validate PR
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test_affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build
