name: Validate PR
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test_affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.4'
      - name: Install dependencies
        run: yarn install
      - run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
      - name: Run platform tests
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Build platform
        run: npx nx affected --target=build --parallel=3
